feat: :lipstick: add button component
nsdonato/front-invoices pull request #20
Opened 2023-01-17 19:46 UTC by Ch3CoX

# 🧾 Invoices App Pull Request

## Descripcion ✏️
* Agregé el **button1** para añadir factura
* Agregé las siguientes dependencias
  * `npm install --save-dev react-icons`
  * `npm install --save-dev @fortawesome/free-solid-svg-icons`
  * `npm install --save-dev @fortawesome/react-fontawesome`

## Cambios visuales 🎨
* Desktop & Tablet
![image](https://user-images.githubusercontent.com/112005385/212996188-c2263c00-528a-4807-b9df-6a74504f70e0.png)
* Mobile
![image](https://user-images.githubusercontent.com/112005385/212996356-c9b78a93-7311-491c-ae1d-2efe85aff998.png)

## Como testear? 🐛

2023-01-17 20:12 UTC, techwithmat commented on src/components/buttons/Button1.tsx
> +    <button className="bg-brand-violet hover:bg-brand-violet-light text-brand-white flex py-1.5 pl-1.5 pr-3.5 rounded-3xl md:py-2 md:pl-2 md:pr-4">
El botón debería tener propiedades tales como onClick, type que se pase por props, ya que se utiliza para abrir modales u otros componentes

2023-01-17 20:17 UTC, techwithmat commented on src/components/buttons/Button1.tsx
> +    <button className="bg-brand-violet hover:bg-brand-violet-light text-brand-white flex py-1.5 pl-1.5 pr-3.5 rounded-3xl md:py-2 md:pl-2 md:pr-4">
Se le podría agregar al botón  las propiedades,  onClick y  type que se pase por props, ya que se utiliza para abrir modales u otros componentes

2023-01-17 20:33 UTC, nsdonato requested changes

2023-01-17 20:33 UTC, nsdonato commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^6.2.1",
No haría falta agregar dependencias extras, ya que en figma podes descargarte el "icono" del + como un svg desde acá:

![image](https://user-images.githubusercontent.com/7875216/213005767-2e0a6838-8ed7-4092-bb0f-1ef028bce199.png)

2023-01-17 20:33 UTC, nsdonato commented on package.json
> +    "react-icons": "^4.7.1",
Esta dependencia también habría que eliminarla teniendo en cuenta lo de arriba

2023-01-17 20:33 UTC, nsdonato commented on src/components/buttons/Button1.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
Tanto el nombre del componente como la carpeta deberían llamarse Button ej:
components/Button/Button.tsx

2023-01-17 23:02 UTC, Ch3CoX commented on package.json
> +    "react-icons": "^4.7.1",
Listo, procedo a corregirlo,..

2023-01-18 03:21 UTC, phreakphreak commented
voy a cerrar este PR ya que ya existe uno creado para este ticket con el branching correcto #22

2023-01-18 03:21 UTC, closed without merging