feat: add button component
nsdonato/front-invoices pull request #22
Opened 2023-01-18 02:55 UTC by Ch3CoX

# 🧾 Invoices App Pull Request

## Descripcion ✏️
* Se agregó un componente `Button.tsx` en la siguiente estructura:

```
src
│   
└───components
    └───button
        └───Button.tsx
```

* Y el test `Button.test.tsx` en:

```
src
│   
└───test
    └───button
        └───Button.test.tsx
```

* Se modificó `App.tsx` agregando el componente `<Button />` para que se visualice en el `main.tsx` 

## Cambios visuales 🎨

### Desktop & Tablet

![image](https://user-images.githubusercontent.com/112005385/213069535-04fce814-e4c7-4a74-b5e5-e2176042290e.png)

### Mobile

![image](https://user-images.githubusercontent.com/112005385/213069754-ddf9cd37-8eaf-45dd-901b-dc05aaa05d5a.png)

## Como testear? 🐛

2023-01-18 03:18 UTC, phreakphreak requested changes

2023-01-18 03:18 UTC, phreakphreak commented on src/components/button/Button.tsx
> +const Button = () => {
los nombres de las carpetas mantengamos que siempre comienzen con mayusculas 🙂

2023-01-18 03:18 UTC, phreakphreak commented on src/tests/button/button.test.tsx
> +import Button from "../../components/button/Button";
aqui podemos usar la misma idea de empezar con mayuscula el nombre del archivo de test asociado a ese componente y el directiorio quizas tambien

2023-01-18 03:34 UTC, maadeval requested changes

2023-01-18 03:34 UTC, maadeval commented on src/components/button/Button.tsx
> +  };
Hola! 👋 Me parece genial que hayas agregado un método para controlar el `onClick` del botón en base a anteriores feedback! 😊 Para que el método se pueda ejecutar independientemente de la acción que haga (sea ejecutar un alert en el navegador, hacer un fetch, etc) necesita ser un método pasado por `props`! 

De esta manera, otros desarrolladores pueden usar tu componente y ejecutar cualquier función al hacerle click, te dejo un ejemplo para que pueda quedar más claro! 👇
```tsx
const Button = ({ onClick }) => {
  return <button onClick={onClick}>...</button>
}

// luego lo usarias en otro componente de esta forma:
...
const handleClick = () => window.alert("Click! 🙌")

return <Button onClick={handleClick}>...<Button>
...
```

De esta manera, cuando se ejecuta el `onClick` del componente, se estará ejecutando realmente `handleClick` 🎉

Si tienes alguna duda, siempre puedes comentar o avisar a algún miembro del equipo para pedir feedback y hacer pair programming (yo también estoy disponible) 🤘

2023-01-18 03:34 UTC, maadeval commented on src/components/button/Button.tsx
> +      <span className="hidden md:block md:text-sm md:py-2">New Invoice</span>
Me gustó que hayas usado tailwind para mostrar u ocultar elementos y seguir los casos de uso en Figma! Esto más que una corrección es una propuesta 🙌:

Se podría permitir que el contenido del botón cambie en base a la prop `children`, de esta manera, el componente va a ser agnostico de si su contenido es `New` o `New Invoice`, cambiandolo por el que el developer quisiera.

Por ejemplo, puede que en un futuro usemos ese mismo botón en otra parte de la app y quieramos cambiar el texto. O apliquemos varios idiomas y que su contenido sea dinamico dependiendo del idioma 🌎

Esto se podría hacer de la siguiente manera:
```tsx
const Button = ({children}) => {
  return <button>{children}</button>
}

// se usaria asi:
<Button>Texto dinamico</Button>
```

Cualquier duda podes comentarlo y ayudamos! 😊

2023-01-18 16:02 UTC, Ch3CoX commented on src/components/button/Button.tsx
> +const Button = () => {
Así de esta forma?
```
src
│   
└───components
    └───Button  -> Carpeta
        └───Button.tsx -> Componente
```

2023-01-18 16:02 UTC, Ch3CoX commented on src/tests/button/button.test.tsx
> +import Button from "../../components/button/Button";
Igual que los componentes?
```
src
│   
└───test
    └───Button -> Carpeta
        └───Button.test.tsx -> Test
```

2023-01-18 18:17 UTC, phreakphreak commented on src/tests/button/button.test.tsx
> +import Button from "../../components/button/Button";
si, me parece que asi podemos identificar mejor al componente que se esta testeando

2023-01-18 18:22 UTC, phreakphreak commented on src/components/button/Button.tsx
> +const Button = () => {
si, para algunos casos a veces necesitamos hacer un import de eg. Button/index.jsx
entonces los imports se harian usando solo nombre del directorio

eg.
`import Button from "./components/Button"`

2023-01-21 06:46 UTC, Ch3CoX commented on src/components/button/Button.tsx
> +      <span className="hidden md:block md:text-sm md:py-2">New Invoice</span>
@maadeval esta fue una forma de poder hacerlo
```jsx
const Button = ({
  variant = "primary",
  buttonLabel,
  widthFull,
  children,
}: Props) => {
  const [isDesktop, setDesktop] = useState(window.innerWidth > 768);

  window.addEventListener("resize", () => {
    setDesktop(window.innerWidth > 768);
  });

  function renderLabel() {
    if (isDesktop) {
      return <span className="my-2 mx-4 pt-px">{buttonLabel}</span>;
    } else {
      return <span className="my-2 mx-2 pt-px">New</span>;
    }
  }

  const handleClick = () => {
    // event
  };

  return (
    <button
      onClick={handleClick}
      className={`text-sm rounded-3xl flex py-2 px-2 
      ${variants[variant as keyof Variants]} 
      ${widthFull ? "w-full justify-center" : ""}`}
    >
      {children}
      {buttonLabel === "New Invoice" ? (
        renderLabel()
      ) : (
        <span className="my-2 mx-4 pt-px">{buttonLabel}</span>
      )}
    </button>
  );
};

export default Button;
```

2023-01-21 07:34 UTC, Ch3CoX commented on src/components/button/Button.tsx
> +  };
@maadeval  Ahora si ya se puede ejecutar el `onclick` desde cualquier otro componente.
```jsx

interface Props {
  variant?: string;
  buttonLabel: string;
  widthFull?: boolean;
  children?: JSX.Element;
  onClick: (event: React.MouseEvent<HTMLButtonElement>) => void;
}

// componente button
const Button = ({
  variant = "primary",
  buttonLabel,
  widthFull,
  children,
  onClick,
}: Props) => {
return (
    <button
      onClick={onClick}
      className={`text-sm rounded-3xl flex py-2 px-2 
      ${variants[variant as keyof Variants]} 
      ${widthFull ? "w-full justify-center" : ""}`}
    >
      {children}
      {buttonLabel === "New Invoice" ? (
        renderLabel()
      ) : (
        <span className="my-2 mx-4 pt-px">{buttonLabel}</span>
      )}
    </button>
  );
};
}

// Otro componente
<Button
    buttonLabel="Mark as Paid"
    onClick={() => {
      console.log("Mark as Paid");
    }}
 />
```

![image](https://user-images.githubusercontent.com/112005385/213848871-77bca198-6f7e-49e7-978a-ce24396e320e.png)

2023-01-23 01:19 UTC, nsdonato commented on src/components/button/Button.tsx
> +      <span className="hidden md:block md:text-sm md:py-2">New Invoice</span>
@phreakphreak  y @maadeval  si los cambios ya están aplicados porfis marquen según corresponda "Resolve Converation" y aprueben, cuando sea posible y tengan un tiempito, muchas gracias <3

2023-01-23 03:06 UTC, maadeval commented on src/components/button/Button.tsx
> +      <span className="hidden md:block md:text-sm md:py-2">New Invoice</span>
Cox muchas gracias por los cambios! ☺️ Pensando en la escalabilidad del proyecto y el componente, los desarrolladores que usen `Button` deberían ser capaces de agregar un texto libre en su interior y evitar que sea modificado por lógica que haya en su interior. Esto evita:
1. Que el desarrollador deba entrar al componente para entender su lógica y que texto puede agregar.
2. Que no haya modificaciones imprevistas del texto por lógica de `addEventListener` y `resize`.

> Siempre pensemos que un componente debe ser lo mas agnóstico y reutilizable posible, por lo que tomar estas acciones ayudan mucho a su reutilización! ✨

Como sugerencia, removería la lógica asociada a `buttonLabel` y permitiria que el contenido del button sea responsabilidad del `children`.

```tsx
const Button = ({ children, onClick }) => {
  return <button onClick ={onClick}>{children}</button>
}

// se usaria asi:
<Button onClick={() => alert("Cox crack! ✨")}>New Invoice</Button>
```

Luego si el texto cambia por media queries, la responsabilidad estara en el CSS del componente padre.

## 🎨 Propuesta Button con SVG 
Como propuesta respecto al botón con SVG, muchas librerías y proyectos toman la decisión de crear un nuevo componente `ButtonIcon` para diferenciar el `Button` común con el que tiene Icon. Esto es una propuesta e idea más relacionada con gustos y toma de decisiones así que es solo una posibilidad que comparto y que puede separar un poco mas la lógica dentro de tu componente 🙌🏻

2023-01-23 03:16 UTC, maadeval requested changes
Recuerda limpiar el contenido agregado en `App` para dejarlo tal cual estaba, esto puede evitar conflictos con otras PRs, muchas gracias por escucharnos y estar mejorando cada vez mas el componente! ☺️

2023-01-23 03:16 UTC, maadeval commented on src/components/Button/Button.tsx
> +  variant?: string;
La prop `variant` debe ser de tipo: `primary`, `secondary`, `tertiary` o `delete`. Puedes definirlo de esta manera:
`variant?: "primary" | "secondary" | "tertiary" | "delete"` y daras aun mas ayuda a los desarrolladores que usen tu componente 🥳

2023-01-23 03:16 UTC, maadeval commented on src/components/Button/Button.tsx
> +  children?: JSX.Element;
JSX.Element es una alternativa para typar `children`, pero tiene algunas limitantes, en cambio `React.ReactNode` nos permite mayores libertades que pueden ser utiles en este componente! Te dejo este link por si quieres verlo mas a detalle: https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement

2023-01-23 03:16 UTC, maadeval commented on src/components/Button/Button.tsx
> +  });
Usar un `addEventListener` en el cuerpo del componente y no dentro de un `useEffect` es peligroso porque cada vez que el componente se vuelva a renderizar, se estara creando un nuevo `addEventListener`. Como recomendacion y en base a esta recomendacion: https://github.com/nsdonato/front-invoices/pull/22#discussion_r1083620596, sera mejor removerlo y evitar un renderizado condicional dentro del componente para controlar el texto 🌈

2023-01-24 02:48 UTC, phreakphreak commented on src/components/Button/Button.tsx
> +  }
como lo comento maadeval esto se puede quitar, igual si necesitas hacer algo en especifico que todo el contenido se pueda enviar desde la prop children

2023-01-24 02:51 UTC, phreakphreak commented on src/components/Button/Button.tsx
> +      {children}
```suggestion
      {children}
```

2023-01-25 08:04 UTC, Ch3CoX commented on src/components/button/Button.tsx
> +      <span className="hidden md:block md:text-sm md:py-2">New Invoice</span>
@maadeval gracias a ti por el feedback, me sirve de mucho ya que voy aprendiendo.
Sobre la **Propuesta Button con SVG** me parece buena idea, pero quise ver una forma donde un `Button` sea capaz de recibir tanto texto como un svg (en el caso del svg tengo una propuesta de crear componentes de estos, como lo hice en el código) en tanto lo que hice en el componente `Button` fue:
```tsx
const Button = ({
  variant = "primary",
  children,
  widthFull,
  onClick,
}: Props) => {
  return (
    <button
      onClick={onClick}
      className={`text-sm rounded-3xl flex items-center py-2 px-2 h-12
      ${variants[variant as keyof Variants]} 
      ${widthFull ? "w-full justify-center" : ""}`}
    >
      {React.Children.map(children, (child) => {
        if (React.isValidElement(child)) {
          return child;
        } else {
          return <span className="mt-[9px] mb-2 mx-4">{child}</span>;
        }
      })}
    </button>
  );
};
```
En el contenido del button agregue un mapeo para recoger todo lo que se pasa al `children` y usar una condicional con la función `isValidElement` para determinar si un elemento es un componente o no.  En caso de que si es un componente lo tomamos como un icono y lo renderizamos ya con los estilos de padding que se le dio al `Button` y en caso contrario lo tomamos como texto y lo encerramos en un span para darle algunos estilos que hará que el texto este centrado de acuerdo al **Design System**
Aquí dejo un ejemplo de cómo se implementaría el componente `Button`
### `Button` con solo texto
```tsx
<Button variant="primary" onClick={() => {console.log("Mark as Paid");}}>
  <PlusCircle size={32} color="white" />
  Mark as Paid
</Button>
```
![image](https://user-images.githubusercontent.com/112005385/214510117-3e94fb05-d086-4194-9d43-89b811a4b4e1.png)
### `Button` con icono a la izquierda y texto
```tsx
<Button variant="primary" onClick={() => {console.log("New Invoice");}}>
  <PlusCircle size={32} color="white" />
  New Invoice
</Button>
```
![image](https://user-images.githubusercontent.com/112005385/214509691-f0929300-1aad-4212-a466-06e469785d29.png)
### `Button` con icono a la derecha y texto
```tsx
<Button variant="primary" onClick={() => {console.log("New Invoice");}}>
  New Invoice
  <PlusCircle size={32} color="white" />
</Button>
```
![image](https://user-images.githubusercontent.com/112005385/214509871-c54d35a1-c9ac-4da9-81ca-233366dada64.png)

2023-01-25 08:07 UTC, Ch3CoX commented on src/components/Button/Button.tsx
> +  });
Tienes mucha razón, ya lo removí..

2023-01-25 08:09 UTC, Ch3CoX commented on src/components/Button/Button.tsx
> +  }
¡Concuerdo! a ver si los cambios que hice están bien, o simplemente debí dejarlo con `children`.

2023-01-25 08:52 UTC, nsdonato commented on src/components/Button/Button.tsx
> +  });
Holis, recordemos que las personas que comenzaron con la conversación son las que pueden dar por resuelta la conversación.  👮🏻 😅 @Ch3CoX

2023-01-25 08:54 UTC, nsdonato approved these changes

2023-01-25 10:04 UTC, maadeval approved these changes
Muchas gracias y muy buen trabajo!! 💪 Quedó todo muy bien implementado 😊

2023-01-25 10:05 UTC, maadeval commented on src/components/Button/Button.tsx
> +  });
Perfecto! ✨

2023-01-25 22:35 UTC, nsdonato approved these changes

2023-01-26 00:57 UTC, merged