feat: :sparkles: feat: add new component (NavBar) to user experience
nsdonato/front-invoices pull request #24
Opened 2023-01-18 22:25 UTC by Boguita

# 🧾 Invoices App Pull Request

## Descripcion ✏️

## Cambios visuales 🎨

## Como testear? 🐛

2023-01-18 23:06 UTC, techwithmat requested changes

2023-01-18 23:06 UTC, techwithmat commented on src/components/NavBar/index.tsx
> +          <img /// Se agrego el logo a la carpeta public y se reemplazo el de Vite
Este comentario podríamos sacarlo, porque los cambios ya reflejan lo que se modificó.

2023-01-18 23:06 UTC, techwithmat commented on src/components/NavBar/index.tsx
> +            src="../../../public/logo.svg"
El directorio /public en Vite sirve los archivos estáticos en el directorio raíz, se puede acceder al archivo directamente con /logo.svg.

2023-01-18 23:06 UTC, techwithmat commented on src/components/NavBar/index.tsx
> +            <svg /// Skeleton de avatar para incio de sesion
Este comentario también podríamos sacarlo.

2023-01-20 20:36 UTC, techwithmat approved these changes
Listo, Esta todo perfecto!

2023-01-20 21:01 UTC, JuaniSilva requested changes
Estaba viendo las screenshots y se ve perfecto. Lo unico que se hace medio raro es que tenga position fixed entonces el contenido de la app queda debajo de la navbar, entiendo que es para que se siga viendo por mas que haya scroll pero me parece que deberia ser estatico y que ocupe ese espacio y que el scroll sea solo dentro del contenido de la app. 

Para que se entienda mejor mi idea, lo que pasría si tiene posición fixed es lo siguiente:
![image](https://user-images.githubusercontent.com/69092286/213803685-5faf4a69-93c8-4379-96c9-69ddc3d9739f.png)
El contenido de la app es lo rosa lo cual se sobrepone la navbar lo cual complicaria, por ejemplo, el posicionamiento en el centro del contenido:
![image](https://user-images.githubusercontent.com/69092286/213804004-3b82e49e-c8a6-47a5-8d87-7262c66b9488.png)

En el caso de que el navbar pase a ocupar realmente el espacio se vería algo así:
![image](https://user-images.githubusercontent.com/69092286/213804220-522f6a34-7d72-4c91-98f9-f1c8d2368d67.png)
y a la hora de centrar el contenido quedaría bien centrado:
![image](https://user-images.githubusercontent.com/69092286/213804362-c60a8116-117a-4cd5-9365-7a4850a8e317.png)

Espero que se haya entendido, no soy muy bueno explicando jajaja

2023-01-20 21:09 UTC, Boguita commented
> Estaba viendo las screenshots y se ve perfecto. Lo unico que se hace medio raro es que tenga position fixed entonces el contenido de la app queda debajo de la navbar, entiendo que es para que se siga viendo por mas que haya scroll pero me parece que deberia ser estatico y que ocupe ese espacio y que el scroll sea solo dentro del contenido de la app.

Holaaa, si se entendio! No estaba seguro si dejarlo asi... Pensaba que podría ponerse un padding al body de manera responsive pero creo es mejor idea dejarlo estatico y que solo se pueda scrollear el resto de la page. No se cual de las dos opciones nos va a complicar mas pero me tiro mas a la que vos decis.

2023-01-23 01:04 UTC, nsdonato requested changes

2023-01-23 01:04 UTC, nsdonato commented on src/components/NavBar/index.tsx
> +    <>
No es necesario el fragment ya que el nav hace de padre

2023-01-23 01:04 UTC, nsdonato commented on src/components/NavBar/index.tsx
> +            <svg
Este svg se podría tratar como el logo y ponerlo en la carpeta public

2023-01-23 01:16 UTC, nsdonato requested changes
Hay dos tareas que hablan del NavBar y tenés asignadas, la que tenga los cambios pedidos debería quedar y la otra ser eliminada o archivada.

2023-01-24 02:23 UTC, phreakphreak requested changes

2023-01-24 19:56 UTC, maadeval requested changes
Hola! 👋 Excelente trabajo!! Hay un detalle súper mínimo y es que en `Dark Mode` el `background-color` del Navbar cambia! 🌚 Si arreglas eso ya quedaria todo perfecto.

Muchas gracias!!

2023-01-25 00:52 UTC, nsdonato requested changes
Porfi, podrás renombrar la rama a feature/task-7 ?  Así respetamos las nomenclaturas de los branchs, gracias <3

PD: también va a afectar en que no va a pasar el workflow de GitHub Actions.

2023-01-25 13:12 UTC, Boguita commented on src/components/NavBar/index.tsx
> +import React from "react";
Listo! :)

2023-01-25 15:43 UTC, closed without merging