Feature/invoice item
nsdonato/front-invoices pull request #30
Opened 2023-01-20 02:03 UTC by AllegriM

# 🧾 Invoices App Pull Request

## Descripcion ✏️

Se agrego el componente exitosamente: InvoiceItem.

## Cambios visuales 🎨

![image](https://user-images.githubusercontent.com/92539373/213602358-65228a0f-ec58-4be2-9ea4-eb3945d822e5.png)

## Como testear? 🐛

N/A

2023-01-20 21:07 UTC, maadeval approved these changes
🥳🥳🥳

2023-01-20 21:13 UTC, JuaniSilva approved these changes
Looks good, tal vez estaría bueno que lo del status sea un componente ya que se usa en otros lados pero tal vez hay otra task que es eso

2023-01-23 00:57 UTC, nsdonato requested changes

2023-01-23 00:57 UTC, nsdonato commented on src/components/InvoiceItem/InvoiceItem.tsx
> +        Due {dateTransformed.replaceAll(",", "")}
Verificar formato, ya que en figma es ej: Due 19 Aug 2021 

![image](https://user-images.githubusercontent.com/7875216/213949675-14387f50-d994-40eb-8411-cc7f9225f9c8.png)

Otras pequeñas cosas a resaltar: podría ser un span. Otras cosas a revisar:
![image](https://user-images.githubusercontent.com/7875216/213949962-005e61fe-8e9b-4043-8029-b3a8269031d3.png)

2023-01-23 00:57 UTC, nsdonato commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  as,
Que sería esto? algo como, le paso el elemento que quiero que sea y sino es un div? de ser así, se podría nomenclar de manera alusiva y si no se pasa nada poner por defecto "div", para evitar la linea 62

2023-01-23 00:57 UTC, nsdonato commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
> +  const invoiceItemElement = screen.getByText("RT3080");
Se deben chequear que estén todos los elementos que conforman el componente, no solo uno.

2023-01-23 00:57 UTC, nsdonato commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
> +// Test if the InvoiceItem component is rendering the correct amount
Eliminar comentarios, esto ya es parte de la descripción del test en la linea 19

2023-01-23 00:57 UTC, nsdonato commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
> +// Test if the InvoiceItem component is rendering the correct status
Eliminar comentario (idem arriba)

2023-01-23 00:57 UTC, nsdonato commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
> +type Status = "paid" | "pending" | "draft";
Estos types no forman parte del componente? Si es así se podrían traer de ahí o si se reutilizan en otro lado se podría crear en una carpeta ej: commons/types y poner ahí.

2023-01-23 00:57 UTC, nsdonato commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
> +  const allStatus = ["paid", "pending", "draft"];
Mismo tema que arriba con los tipos, poderemos chequearlo?

2023-01-23 21:36 UTC, AllegriM commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  as,
Correcto! Al elemento se lo llama como InvoiceItem y se le puede pasar una propiedad **as** que va a tener como opciones: 

- Link
- a
- div (DEFAULT)

![image](https://user-images.githubusercontent.com/92539373/214155005-8275d951-27ac-45fc-9a8f-07516d2fc150.png)

Y en la linea 62 especifica que si no se le pasa as como prop ponga un div.

Magia de Made

2023-01-24 01:04 UTC, phreakphreak commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
con el tema de Link no estamo abstrayendo demas? bien podemos usar Link de manera wrapped 🤔

2023-01-24 01:06 UTC, phreakphreak requested changes

2023-01-24 01:06 UTC, phreakphreak commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
>  test("renders InvoiceItem component", () => {
al tener la funcionalidad de typeOfElement faltarian unos test para testear si la etiqueta renderizada esta funcionando correctamente

2023-01-24 01:08 UTC, AllegriM commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
>  test("renders InvoiceItem component", () => {
Me parece correcto. Mañana lo hago!!

2023-01-24 01:09 UTC, AllegriM commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
No estaria entendiendo esto 🤔

2023-01-24 01:15 UTC, phreakphreak commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
eg. mi duda va mas de como usarlo con Link, nose si lo estoy implementando bien 🤔
![image](https://user-images.githubusercontent.com/91038818/214192763-1a67491f-e8bf-42dd-afdd-2f29294e71b2.png)

2023-01-24 01:18 UTC, phreakphreak commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
con las etiquetas a y div no hay problemas, pero con Link no se si deberia pasarlo de cierta manera

2023-01-24 01:18 UTC, AllegriM commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
Se usaria asi.
![image](https://user-images.githubusercontent.com/92539373/214193325-1cb24c38-ec86-490f-bdc8-98031ea39e01.png)

2023-01-24 01:23 UTC, phreakphreak commented on src/components/InvoiceItem/InvoiceItem.tsx
> +  typeOfElement?: C extends "div" | "a" | typeof Link ? C : never;
ahh ok me quedo mucho mas claro

2023-01-25 21:00 UTC, AllegriM commented on src/tests/InvoiceItem/InvoiceItem.test.tsx
>  test("renders InvoiceItem component", () => {
Tests realizados!! Espero revision jejee!!

2023-01-25 22:44 UTC, nsdonato approved these changes

2023-01-25 23:01 UTC, merged