Feature: Modal Component
nsdonato/front-invoices pull request #31
Opened 2023-01-20 21:58 UTC by JuaniSilva

# 🧾 Invoices App Pull Request

## Descripcion ✏️
En este pr cree el componente del modal. El componente requiere que se le pase ciertos props como `show`, `onCloseAction` y `title`, luego el contenido que se ve en el modal es completamente custom, es decir, que hay que pasarle lo que queremos que se muetre dentro del componente.

## Cambios visuales 🎨
preview del modal:
![brave_UhsNF6JKmD](https://user-images.githubusercontent.com/69092286/213812505-d6a8f423-7230-4108-97b9-2bba382ec5ff.gif)

## Como testear? 🐛

2023-01-20 22:44 UTC, techwithmat approved these changes

2023-01-23 00:45 UTC, nsdonato requested changes

2023-01-23 00:45 UTC, nsdonato commented on src/components/Modal/Modal.test.tsx
> +      <Modal title="Modal test" show={true} onCloseRequest={handleClick}>
No faltaría un test para cuando se utiliza el onCloseRequest? (aunque entiendo que es lo mismo que hacer click en el backdrop, debería hacerse para verificar que la fución de ocultar este bien

2023-01-23 00:45 UTC, nsdonato commented on src/components/Backdrop/Backdrop.tsx
> +      className={`absolute top-0 left-0 w-full h-full bg-black/25 flex items-center justify-center
Verificando figma, el backdrop debería ser de color #979797, revisé la config de Tailwind y no estaba, así que habría que agregarlo. también habría que mantener la opacidad especifica del diseño para respetarlo lo más posible

![image](https://user-images.githubusercontent.com/7875216/213949100-0f798ac9-0a96-4f82-a403-da40da098469.png)

2023-01-23 00:45 UTC, nsdonato commented on src/components/Modal/Modal.tsx
> +          <h4 className="text-[24px] font-bold">{title}</h4>
Se puede chequear si la fuente utilizada es la Spartan y el color es el correcto?

2023-01-23 00:45 UTC, nsdonato commented on src/components/Backdrop/Backdrop.test.tsx
> +    expect(show).toBe(false);
Creo que se debería chequear que aparte de que la variable show este en false, que realmente no se muestre el backdrop.

```suggestion
    expect(show).toBe(false);
    expect(backdrop).not.toBeInTheDocument()
```

2023-01-23 18:56 UTC, JuaniSilva commented on src/components/Backdrop/Backdrop.tsx
> +      className={`absolute top-0 left-0 w-full h-full bg-black/25 flex items-center justify-center
Probé con ese color y opacidad y quedaba muy clarito y luego me di cuenta que ese color es del stroke que sería el borde y esta oculto. 
![image](https://user-images.githubusercontent.com/69092286/214030084-db970545-d952-42f7-8082-65fc724408c4.png)

El color es el fill que es completamente negro con esa opacidad que si esta en la config y ya lo cambie a ese y queda igual. El color esta como `dark-ghost`

2023-01-23 18:56 UTC, JuaniSilva commented on src/components/Modal/Modal.tsx
> +          <h4 className="text-[24px] font-bold">{title}</h4>
Faltaba el color, estaba en negro completamente
![image](https://user-images.githubusercontent.com/69092286/214030586-39f05b39-9527-417d-b5e8-13b53ac0f9e4.png)

2023-01-23 18:57 UTC, JuaniSilva commented on src/components/Backdrop/Backdrop.test.tsx
> +    expect(show).toBe(false);
añadí un test que chequea si tiene las clases correspondientes cuando no se muestra

2023-01-23 18:58 UTC, JuaniSilva commented on src/components/Modal/Modal.test.tsx
> +      <Modal title="Modal test" show={true} onCloseRequest={handleClick}>
la verdad no se como agregar un test para esto ya que lo unico que hace esa prop es pasársela al backdrop

2023-01-23 23:33 UTC, phreakphreak commented on src/components/Modal/Modal.tsx
> +
Aqui lo comento pero seria un hook asi pero en otro archivo para poder usarlo independiente de que elemento este, lo del useCallback es mas una propuesta
```suggestion
import { useCallback, useEffect } from "react";

const KEY_NAME_ESC = "Escape";
const KEY_EVENT_TYPE = "keydown";

export function useEscapeKey(handleClose: () => void) {
  const handleEscKey = useCallback(
    (event: Event) => {
      if (event instanceof KeyboardEvent && event.key === KEY_NAME_ESC) {
        handleClose();
      }
    },
    [handleClose]
  );

  useEffect(() => {
    document.addEventListener(KEY_EVENT_TYPE, handleEscKey, false);

    return () => {
      document.removeEventListener(KEY_EVENT_TYPE, handleEscKey, false);
    };
  }, [handleEscKey]);
}

```

2023-01-23 23:34 UTC, phreakphreak commented on src/components/Modal/Modal.tsx
> +
Aqui lo comento pero seria un hook asi pero en otro archivo para poder usarlo independiente de que elemento este, lo del useCallback es mas una propuesta
```suggestion
import { useCallback, useEffect } from "react";

const KEY_NAME_ESC = "Escape";
const KEY_EVENT_TYPE = "keydown";

export function useEscapeKey(handleClose: () => void) {
  const handleEscKey = useCallback(
    (event: Event) => {
      if (event instanceof KeyboardEvent && event.key === KEY_NAME_ESC) {
        handleClose();
      }
    },
    [handleClose]
  );

  useEffect(() => {
    document.addEventListener(KEY_EVENT_TYPE, handleEscKey, false);

    return () => {
      document.removeEventListener(KEY_EVENT_TYPE, handleEscKey, false);
    };
  }, [handleEscKey]);
}


```

2023-01-23 23:35 UTC, JuaniSilva commented on src/components/Modal/Modal.test.tsx
> +      <Modal title="Modal test" show={true} onCloseRequest={handleClick}>
ahora cuando se apreta escape teniendo el modal abierto se llama a un metodo llamado `handleKeyDown` y ahí se llama a `onCloseRequest`. Agrege un test que testea este caso :D

2023-01-23 23:35 UTC, phreakphreak commented on src/components/Modal/Modal.tsx
> +  const handleKeydown = (event: React.KeyboardEvent) => {
en lugar del handlerevent
```suggestion
   useEscapeKey(onCloseRequest);
```

2023-01-23 23:42 UTC, phreakphreak commented on src/components/Backdrop/Backdrop.test.tsx
> +import { render, screen } from "@testing-library/react";
los test no estarian mejor en la carpeta de tests 🤔🤔?  asemejandose a la estructura del proyecto eg. src/tests/components/Backdrop/Backdrop.test.tsx

2023-01-24 00:18 UTC, phreakphreak requested changes

2023-01-24 00:18 UTC, phreakphreak commented on src/components/Modal/Modal.tsx
> +  show,
aqui tengo unas dudas, el estado del modal siempre sera dependiendo de algun componente parent? o este modal es capaz de manejares internamente con su propio state

2023-01-24 00:20 UTC, phreakphreak commented on src/components/Modal/Modal.tsx
> +  show,
segun la implementacion de los test, me dicen que un componente parent del modal tendria estas variables y operaciones que alteren su comportamiento 🤔?, es mas duda de implementacion

2023-01-24 11:05 UTC, JuaniSilva commented on src/components/Backdrop/Backdrop.test.tsx
> +import { render, screen } from "@testing-library/react";
Yo tome como ejemplo el componente de EmptyState que tiene el test y el componente en la misma carpeta. Pero si, a mi me parece mas organizado de esa forma.

2023-01-24 11:09 UTC, JuaniSilva commented on src/components/Modal/Modal.tsx
> +  show,
Si, asi es. Ahora mismo todo esto lo maneja el padre, tanto si se muestra o no y la funcion de cuando se quiere cerrar el modal.

Por ejemplo yo para testearlo tengo todo en `App.tsx`
![image](https://user-images.githubusercontent.com/69092286/214276576-a588c595-0b0f-43cf-9fd7-a990c90e3a96.png)

2023-01-24 12:53 UTC, phreakphreak approved these changes

2023-01-25 22:39 UTC, nsdonato approved these changes

2023-01-26 12:00 UTC, merged