Features/filter issue 26
nsdonato/front-invoices pull request #34
Opened 2023-01-25 07:13 UTC by rretta

# 🧾 Invoices App Pull Request

## Descripcion ✏️
 Se agrega componente Filter  en conjunto con el componente SvgImg que sirve para traer un .svg al Filter. (flechas ^ v )

## Cambios visuales 🎨

preview del componente: 

![previewfilter](https://user-images.githubusercontent.com/87555292/214500925-1aa7d0f0-3efa-4693-892b-48193590f118.gif)

 

## Como testear? 🐛

El componente maneja el siguiente useState de manera interna, luego de ser integrado al resto de la app esta info deberia llegar por props.
```
  const [filterType, setFilterType] = useState({
    draft: false,
    paid: false,
    pending: false,
  });

```

2023-01-27 00:17 UTC, maadeval requested changes
A nivel visual hay un detalle super chico y es que al hacer `hover` en una opcion (o su texto), el border del checkbox se pinta! 

Adjunto un ejemplo de figma:

<img width="809" alt="Captura de pantalla 2023-01-26 a la(s) 21 09 15" src="https://user-images.githubusercontent.com/55862658/214978401-5b7d07b0-5ab9-4a4f-8731-f328ca7734e8.png">

Por otro lado, si le haces doble click al texto del label para checkear y deschekear el checkbox, veras que el texto se selecciona! Para evitar esto podes usar una propiedad de CSS llmada `user-select`:
```css
user-select: none;
```

Esto evita que el usuario pueda seleccionar el texto. Suele ser una buena practica para estos casos en donde es muy incomodo visualmente, pero no hay que abusar de el! Solo para casos concretos 😊

🔗 Link de user-select: https://developer.mozilla.org/es/docs/Web/CSS/user-select

Muchas gracias por todo el trabajo!! 🚀 Se nota que hubo mucho esfuerzo y se valora muchisimo 😊

2023-01-27 00:17 UTC, maadeval commented on src/components/Filter/Filter.tsx
> +  selectFilter: any;
Holis!! 👋 Muy bien incluyendo los tipos para las props del componente!!! Eso ayuda muchisimo para que los desarrolladores sepan si estan pasando valores correctos o incorrectos al componente y evitar errores 🤘

El `any` permite que a `toggleOpen`, `filtersType` y `selectFilter` se le pueda pasar cualquier tipo de valor y que VSCode no nos advierta que eso es un error. Por ejemplo, en `filtersType` por como esta estructurado nuestro componente, necesita que sea un objeto con determinadas propiedades, pero por ser de tipo `any` le podriamos pasar un booleano y nuestro componente se romperia sin darnos aviso de ello.

Para solucionar esto haria falta tiparlo con los valores que necesita, si nos vamos al hook `useFilter` podemos hacer lo siguiente para obtener los tipos:

<img width="935" alt="Captura de pantalla 2023-01-26 a la(s) 20 49 07" src="https://user-images.githubusercontent.com/55862658/214977726-05f84244-4b30-4963-8788-eb309b7721c7.png">

Y luego de copiar ese tipo volveriamos al componente para pegarlo:

<img width="935" alt="Captura de pantalla 2023-01-26 a la(s) 20 54 35" src="https://user-images.githubusercontent.com/55862658/214977781-845e7f65-c07d-413f-abd8-7731c0bd4e58.png">

> Esto con cada una de las props que tienen `any` 🎉

## 🤔 Que pasara a partir de aqui?
Limitaremos a los desarrolladores a pasar los valores que tengan que pasar y evitaremos errores en nuestro codigo! ✅

2023-01-27 03:47 UTC, rretta commented on src/components/Filter/Filter.tsx
> +  selectFilter: any;
ahí generé todos los cambios que se pidió

2023-01-27 09:09 UTC, nsdonato requested changes

2023-01-27 09:09 UTC, nsdonato commented on src/components/Filter/Filter.tsx
> +    pending: boolean;
@maadeval @rretta les parece que pasemos esto a strings? Lo pienso por el lado de que para poder utilizar el endpoint de obtención de facturas, tendríamos que agregar un query string con algo como /invoices?filter=draft,pending 

Que les parece?

2023-01-27 16:01 UTC, maadeval commented on src/components/Filter/Filter.tsx
> +    pending: boolean;
Noee <3  Decis algo como esto? 🤔
```tsx
filtersType: string
```
Tando en `Filter` como `useFilters`?

2023-01-27 16:22 UTC, noeliadv commented on src/components/Filter/Filter.tsx
> +    pending: boolean;
> Noee <3 Decis algo como esto? 🤔
> 
> ```tsx
> filtersType: string
> ```
> 
> Tanto en `Filter` como `useFilters`?

export type Status = "pending" | "paid" | "draft";

De hecho ya esta en el componente InvoiceItem, si se puede reutilizar podemos los tipos que sean comunes en un carpeta commons, que les parece?

2023-01-27 22:45 UTC, rretta commented on src/components/Filter/Filter.tsx
> +    pending: boolean;
ahí cambié el `filterView` dentro del hook y ahora filterType es un array de los elementos checked

```
const [filterType, setFilterType] = useState<Status[]>([]);


  const filterView = (event: React.ChangeEvent<HTMLInputElement>) => {

    if(event.target.checked){
      const newFilterType = [...filterType];
      newFilterType.push(event.target.name as Status);
      setFilterType(newFilterType);
    } else{
      setFilterType(filterType.filter(item => item !== event.target.name));
    }
    
  };

```

2023-01-27 22:50 UTC, nsdonato commented on src/components/Filter/Filter.tsx
> +  selectFilter: any;
Genial! faltaría actualizar los test, que es lo que está rompiendo en el workflow de las actions y ya estaría para aprobar 🚀

2023-01-28 00:30 UTC, maadeval approved these changes
🚀🚀🚀

2023-01-28 00:31 UTC, nsdonato approved these changes

2023-01-28 00:37 UTC, merged

2023-01-28 00:42 UTC, maadeval commented
VAAAMOOSSSSS 🚀