feature/Date Picker #13
nsdonato/front-invoices pull request #38
Opened 2023-01-25 19:48 UTC by NeilChavez

# 🧾 Invoices App Pull Request

## Descripcion ✏️
Es un draft del component DatePicker

## Cambios visuales 🎨
preview del componente:

![DatePicker](https://i.ibb.co/RBdSHB7/Recording-2023-01-25-at-14-18-42.gif "Gif datePicker")

## Como testear? 🐛
me falta el testing, estoy viendo y leendo la documentacion de testing library para hacerlo.

2023-01-25 22:50 UTC, nsdonato commented
Si tenés alguna duda con React Testin Library, no dudes de ponerla en el canal de Testing y te damos una mano!

2023-01-28 01:27 UTC, NeilChavez commented
## Descripcion ✏️
He completado el componente DatePicker

## Cambios visuales 🎨
preview del componente:

![DatePicker](https://i.ibb.co/JCz493L/pr-date-picker.gif"Gif datePicker")


## Como testear? 🐛
n/a

creo que me fallo' el check "Workflow for PRs / 🚀 Vercel Preview Deployment (pull_request) Failing after 16s", como se podria solucionar? 🥲

2023-01-28 23:23 UTC, maadeval requested changes
Hola! 👋
Primero que nada, felicitaciones porque hiciste un trabajo increible!! 🚀🚀 Era uno de los componentes mas dificiles y quedo genial 😊

Por otro lado, me gustaria comentarte un problema (con solucion) que podriamos tener, y es que el estado de la fecha seleccionada lo estas controlando dentro del componente, por lo que si luego queremos usar ese estado para renderizar otros componentes o enviar un formulario, no lo tendremos accesible.

Te comparto una solucion para mitigar esto, recorda que hay varios caminos y si encontras otro que te guste mas, adelante!! 🙌 

## 1️⃣ Lo usariamos de esta forma
```tsx
function App() {
  const [date, setDate] = useState(new Date());

  return (
    <div>
      <>
        <p>Welcome to Invoice App</p>
        <Outlet />
        <DatePicker initialDate={date} onChangeDate={setDate} />
      </>
    </div>
  );
}
```

## 2️⃣ Lo implementariamos de la siguiente
```tsx
interface Props {
  onChangeDate: React.Dispatch<React.SetStateAction<Date>>;
  initialDate?: Date;
}

export default function DatePicker({
  initialDate = new Date(),
  onChangeDate,
}: Props) {
  const [isFocusedInput, setFocusedInput] = useState<boolean>(false);
  const inputElement = useRef(null);
  const calendar = useRef<HTMLDivElement>(null);

  const handleClickInput = () => {
    setFocusedInput((prevState) => !prevState);
  };

  const handleClickDate = (day: number, month: number, year: number) => {
    const newDate = new Date(year, month, day);
    onChangeDate(newDate);
  };

...
// debajo simplemente sustituimos la variable `date` que habia antes por `initialDate` y listo!
...
```
> Lo que se hizo fue remover el estado relacionado a `date` dentro del componente e implementar por props tanto su `state` como su `setter` 👀 

Te parece hacer ese cambio?

Muchas gracias por todo tu trabajo!! 🤘

2023-01-29 16:10 UTC, NeilChavez commented
Hola Maadeval!
Me parece que tienes toda la razon, el estado de "date" tiene que ser controlado desde a fuera del componente.  🙌

Voy a hacer lo relativos cambios

La solucion que compartiste es muy clara y te agradezco mucho por el feedback 😀

2023-01-29 21:34 UTC, closed without merging