add Dropdown component to choose payment day terms
nsdonato/front-invoices pull request #42
Opened 2023-01-27 03:26 UTC by AllegriM

# 🧾 Invoices App Pull Request

## Descripcion ✏️

Se agrego el componente Dropdown para elegir el plazo de pago. Tiene 4 opciones: 

- Net 1 day
- Net 7 days
- Net 14 days
- net 30 days

## Cambios visuales 🎨

*El cambio de color en el texto se da al hacerle hover*

**_LightMode:_** 

![image](https://user-images.githubusercontent.com/92539373/215003376-3f12e37e-e84e-4201-ae2d-ce0b3c6acfb0.png)

**_DarkMode:_** 

![image](https://user-images.githubusercontent.com/92539373/215003497-db2075ca-bf80-4d53-8210-024898bc7380.png)

## Como testear? 🐛
N/A

2023-01-30 17:07 UTC, nsdonato approved these changes

2023-02-01 05:25 UTC, ivanlolivier commented
Buen trabajo!

2023-02-01 20:27 UTC, AllegriM commented
>

2023-02-01 20:30 UTC, AllegriM commented
> Buen trabajo! Pregunta, si el dropdown esta abierto y haces clic en la pantalla (afuera del dropdown), este no se cierra, no? debería?

Buena pregunta. El que yo diseñe no se cierra al hacer click afuera y talvez es molesto. Aunque tambien es molesto que se cierre cuando apretas afuera talvez. Nose en terminos de UX cual sera mejor, pero se podria modificar. En el figma creo que no figura nada sobre si abre o cierra al clickear afuera.

Escucho propuestas.

2023-02-04 14:47 UTC, nsdonato requested changes

2023-02-04 14:47 UTC, nsdonato commented on src/components/Dropdown/Dropdown.tsx
> +        Net {paymentTerm} {paymentTerm === 1 ? "day" : "days"}
day y days con D mayus, mala mia que en la tara lo escribí en minúscula, pero en Figma están con mayus.

2023-02-04 14:47 UTC, nsdonato commented on src/tests/Drowpdown/Dropdown.test.tsx
> +  expect(dropdownElement).toHaveTextContent("Net 1 day");
Podes usar Regex, entonces si cambia alguna letra, no está atado a la integración.

```suggestion
  expect(dropdownElement).toHaveTextContent(/Net 1 day/i);
```

2023-02-08 19:32 UTC, AllegriM commented on src/tests/Drowpdown/Dropdown.test.tsx
> +  expect(dropdownElement).toHaveTextContent("Net 1 day");
Corregido!!

2023-02-08 19:53 UTC, phreakphreak approved these changes

2023-02-08 21:41 UTC, nsdonato approved these changes

2023-02-08 22:13 UTC, closed without merging